import { useState } from 'react';
import { ExternalLink, FileText, ImagePlus, Plus, Trash2 } from 'lucide-react';
import { api } from '../lib/api.js';
import { useFetch } from '../lib/hooks.js';
import { date } from '../lib/format.js';
import { Badge, Button, Card, Empty, Field, Input, Modal, PageHeader, Select, Spinner, Table, Textarea, Thumb, useAction, useToast } from '../components/ui.jsx';
import { MediaPicker } from '../components/MediaPicker.jsx';
import RichText from '../components/RichText.jsx';

// Pages built by the shop itself (cart, checkout…) only expose their title and SEO
const SYSTEM = ['cart', 'checkout', 'my-account', 'shop', 'wishlist', 'order-tracking', 'blog', 'home'];

function Editor({ kind, id, onClose, onSaved }) {
  const { data } = useFetch(id ? `/admin/${kind}/${id}` : null);
  const [doc, setDoc] = useState(id ? null : { title: '', content: '', status: 'publish', seo: {}, excerpt: '' });
  const [picker, setPicker] = useState(false);
  const [run, busy] = useAction();
  const { confirm } = useToast();
  if (id && data && !doc) setDoc({ ...data, seo: data.seo || {} });
  const system = kind === 'pages' && doc && SYSTEM.includes(doc.slug);
  const url = doc ? (kind === 'posts' ? `/${doc.slug}/` : doc.slug === 'home' ? '/' : `/${doc.slug}/`) : '';
  return (
    <Modal open onClose={onClose} width={900} title={id ? `Edit ${kind === 'posts' ? 'article' : 'page'}` : `New ${kind === 'posts' ? 'article' : 'page'}`}
      footer={doc && <>
        {id && !system && <Button variant="danger" icon={Trash2} className="mr-auto" onClick={async () => {
          if (!(await confirm({ title: `Delete "${doc.title}"?`, danger: true, confirmLabel: 'Delete' }))) return;
          await run(() => api.del(`/admin/${kind}/${id}`), 'Deleted');
          onSaved();
        }}>Delete</Button>}
        {id && <a href={url} target="_blank" rel="noreferrer"><Button icon={ExternalLink}>View</Button></a>}
        <Button onClick={onClose}>Cancel</Button>
        <Button variant="primary" loading={busy} onClick={async () => { await run(() => (id ? api.put(`/admin/${kind}/${id}`, doc) : api.post(`/admin/${kind}`, doc)), 'Saved'); onSaved(); }}>Save</Button>
      </>}>
      {!doc ? <Spinner /> : (
        <div className="space-y-3">
          <div className="grid grid-cols-3 gap-3">
            <Field label="Title" className="col-span-2"><Input value={doc.title} onChange={(e) => setDoc({ ...doc, title: e.target.value })} /></Field>
            <Field label="Status"><Select value={doc.status} onChange={(e) => setDoc({ ...doc, status: e.target.value })}><option value="publish">Published</option><option value="draft">Draft</option></Select></Field>
          </div>
          <Field label="URL" hint={`poudrebeauty.com${url}`}><Input value={doc.slug || ''} disabled={system} onChange={(e) => setDoc({ ...doc, slug: e.target.value })} placeholder="generated from the title" /></Field>
          {kind === 'posts' && (
            <div className="flex gap-3">
              <button type="button" onClick={() => setPicker(true)}>{doc.image ? <Thumb src={doc.image} size={96} /> : <div className="flex h-24 w-24 items-center justify-center rounded border border-dashed border-zinc-300 text-zinc-400"><ImagePlus size={18} /></div>}</button>
              <Field label="Summary" className="flex-1"><Textarea rows={3} value={(doc.excerpt || '').replace(/<[^>]+>/g, '')} onChange={(e) => setDoc({ ...doc, excerpt: e.target.value })} /></Field>
            </div>
          )}
          {system ? <p className="rounded-md bg-zinc-50 p-3 text-zinc-600">This page is generated by the shop (products, cart, account…). You can change its title and search engine texts here.</p>
            : <Field label="Content"><RichText value={doc.content} onChange={(content) => setDoc({ ...doc, content })} minHeight={320} /></Field>}
          <div className="grid grid-cols-2 gap-3">
            <Field label="Google title"><Input value={doc.seo?.title || ''} onChange={(e) => setDoc({ ...doc, seo: { ...doc.seo, title: e.target.value } })} placeholder={doc.title} /></Field>
            <Field label="Google description"><Input value={doc.seo?.description || ''} onChange={(e) => setDoc({ ...doc, seo: { ...doc.seo, description: e.target.value } })} /></Field>
          </div>
          <MediaPicker open={picker} onClose={() => setPicker(false)} onPick={([m]) => setDoc({ ...doc, image: m.url })} />
        </div>
      )}
    </Modal>
  );
}

export default function Pages({ kind = 'pages' }) {
  const { data, reload } = useFetch(`/admin/${kind}`);
  const [edit, setEdit] = useState(null);
  const label = kind === 'posts' ? 'Blog' : 'Pages';
  return (
    <>
      <PageHeader title={label} subtitle={kind === 'posts' ? 'Articles shown on the blog' : 'About, contact, terms and every other page of the website'}
        actions={<Button variant="primary" icon={Plus} onClick={() => setEdit({ id: null })}>{kind === 'posts' ? 'New article' : 'New page'}</Button>} />
      <Card padded={false}>
        {!data ? <Spinner /> : (
          <Table rows={data} onRowClick={(r) => setEdit({ id: r.id })} empty={<Empty icon={FileText} title="Nothing yet" />} columns={[
            { key: 'title', label: 'Title', render: (r) => <div className="flex items-center gap-3">{kind === 'posts' && <Thumb src={r.image} size={36} />}<span className="font-medium">{r.title}</span></div> },
            { key: 'slug', label: 'URL', render: (r) => <span className="text-zinc-500">/{r.slug}/</span> },
            { key: 'status', label: 'Status', render: (r) => <Badge tone={r.status === 'publish' ? 'green' : 'gray'}>{r.status === 'publish' ? 'Published' : 'Draft'}</Badge> },
            { key: 'updated_at', label: kind === 'posts' ? 'Published' : 'Edited', align: 'right', render: (r) => date(r.published_at || r.updated_at) },
          ]} />
        )}
      </Card>
      {edit && <Editor kind={kind} id={edit.id} onClose={() => setEdit(null)} onSaved={() => { setEdit(null); reload(); }} />}
    </>
  );
}
